name: Build and Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y cmake build-essential

    - name: Configure
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --target havo -j 10

    - name: Zip osmon std folder
      run: zip -r build/library.zip library

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/libhavo.so
          include/libhavo.h
          build/library.zip
